version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: backend-challenge-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: backend_challenge
    volumes:
      - mongodb_data:/data/db
      - ../scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo-express:
    image: mongo-express
    container_name: backend-challenge-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend-network

  http-server:
    build:
      context: ..
      dockerfile: Dockerfile.http
    container_name: backend-challenge-http
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  grpc-server:
    build:
      context: ..
      dockerfile: Dockerfile.grpc
    container_name: backend-challenge-grpc
    restart: unless-stopped
    ports:
      - "9090:9090"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - backend-network

volumes:
  mongodb_data:
    driver: local

networks:
  backend-network:
    driver: bridge
